/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractAddresses_97 } from './97'
export type ContractAddressesKey = keyof typeof ContractAddresses
export const ContractAddresses = {
  97: ContractAddresses_97
}